#!/bin/bash

# HustleClub Database Setup Helper
# This script provides instructions for setting up the Supabase database schema

echo "🚀 HustleClub Database Setup"
echo "============================"
echo ""
echo "To fix the 'Could not find the table public.clipping_jobs' error:"
echo ""
echo "1. Open your Supabase project dashboard:"
echo "   https://supabase.com/dashboard/project/YOUR_PROJECT_REF"
echo ""
echo "2. Navigate to SQL Editor in the left sidebar"
echo ""
echo "3. Click 'New Query' button"
echo ""
echo "4. Copy and paste the entire contents of database-schema.sql"
echo ""
echo "5. Click the 'RUN' button (or press Ctrl+Enter)"
echo ""
echo "6. Wait for the query to complete successfully"
echo ""
echo "7. Verify the tables were created:"
echo "   - Go to Table Editor"
echo "   - Check for: profiles, courses, clipping_jobs, thrift_items"
echo ""
echo "8. Restart your Next.js development server:"
echo "   - Stop the current server (Ctrl+C)"
echo "   - Run: npm run dev"
echo ""
echo "Expected result after setup:"
echo "✅ /clipping page loads without 'table not found' errors"
echo "✅ Empty state shows if no jobs exist yet"
echo "✅ Dashboard pages work correctly"
echo ""
echo "📁 Schema file location: ./database-schema.sql"
echo "🔗 Supabase Dashboard: https://supabase.com/dashboard"
echo ""